services:
  - type: web
    name: Flask-app
    env: Docker
    buildCommand: docker build -t flask-app .
    startCommand: docker run -p 10000:5000 flask-app
    envVars:
      - key: PORT
        value: 10000