services:
- type: web
  name: flask-app
  env: python
  buildCommand: |
    pip install -r requirements.txt
    pip install --upgrade pip
  startCommand: python3.10 app.py
  envVars:
  - key: PORT
    value: 10000